# Generated by Django 4.2.11 on 2024-04-26 03:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscribers_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='source',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sm', 'Social Media'), ('news', 'News')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subcategory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('npr', 'New Product Releases'), ('ma', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='industry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ch', 'Consumer Health'), ('beauty', 'Beauty'), ('tech', 'Tech')], max_length=100, null=True),
        ),
    ]
