# Generated by Django 4.2.11 on 2024-04-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscribers_source_subscribers_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
